### ISSUE TITLE
slave-thread-1.1.0.1 fails to build with ghc-9.4.3 in Stackage Nightly

### ISSUE THREAD

**Issue by juhp** [nikita-volkov/slave-thread#21]
```
Building library for slave-thread-1.1.0.1..                                                                                         
[2 of 3] Compiling SlaveThread.Util.LowLevelForking                                                                                 
                                                                                                                                    
/var/stackage/work/unpack-dir/unpacked/slave-thread-1.1.0.1-e44d3b021b56afe4f5b2667762dcb022e07ed44a307766aee822fc7aba37900b/library
/SlaveThread/Util/LowLevelForking.hs:12:26: error:                                                                                  
    • Couldn't match expected type: ghc-prim-0.9.0:GHC.Prim.State#                                                                  
                                      RealWorld                                                                                     
                                    -> (# ghc-prim-0.9.0:GHC.Prim.State# RealWorld, a0 #)                                           
                  with actual type: IO ()                                                                                           
    • In the first argument of ‘fork#’, namely ‘action’                                                                             
      In the expression: fork# action s                                                                                                   In the expression:                                                                                                            
        case (fork# action s) of (# s', tid #) -> (# s', ThreadId tid #)                                                            
   |                                                              
12 |   IO $ \s -> case (fork# action s) of (# s', tid #) -> (# s', ThreadId tid #)                                                  
   |                          ^^^^^^                 
```

**Comment by nikita-volkov** [comment]
Thanks for the report. Should be fixed in 1.1.0.2

**Comment by juhp** [comment]
Cool - if you can open a PR to add it back to Stackage Nightly that would be welcome, thanks

**Comment by nikita-volkov** [comment]
Done! :)
